/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import models.HocSinh;
import services.MysqlConnection;
import views.PhatThuongManagerFrame.DipDacBietJFrame;
import views.PhatThuongManagerFrame.PTCuoiNamJFrame;
import views.PhatThuongManagerFrame.PTDacBietJrame;
import views.PhatThuongManagerFrame.QuanLyPhanQuaJFrame;

/**
 *
 * @author TNTDT
 */
public class PhatThuongManagePanel extends javax.swing.JPanel {

    private JFrame parentFrame;
    DefaultTableModel tableModel;
    List<HocSinh> lstHs;

    /**
     * Creates new form HoKhauManagePanel
     *
     * @param parentFrame
     */
    public PhatThuongManagePanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        tableModel = (DefaultTableModel) tblQua.getModel();
        tblQua.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        tblQua.setRowHeight(30);
        tblQua.validate();
        tblQua.repaint();
        tblQua.setFont(new Font("Arial", Font.PLAIN, 14));
        tblQua.getColumnModel().getColumn(0).setMaxWidth(40);
        tblQua.getColumnModel().getColumn(0).setMinWidth(40);
        tblQua.getColumnModel().getColumn(0).setPreferredWidth(80);
        show();
    }

    /**
     * Creates new form PhatThuongManagePanel
     */
    public void show() {
        Connection conn = null;
        Statement stm = null;

//        try {
//            conn = MysqlConnection.getMysqlConnection();
//            String sql1 = "select IDHS, hoTen, count(IDHS, hoTen) as tongQua "
//                    + "from pt_dip_dac_biet and nhan_khau where IDHS = ID";
//            PreparedStatement pstmt = conn.prepareStatement(sql1);
//            ResultSet rs = pstmt.executeQuery();
//            tableModel.setRowCount(0);
//            while (rs.next()) {
//                tableModel.addRow(new Object[]{
//                    tableModel.getRowCount() + 1,
//                    rs.getString("ID"),
//                    rs.getInt("hoTen"),
//                    rs.getInt("tongQua")
//                });
//            }
//            tableModel.fireTableDataChanged();
//
//        } catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(PhatThuongManagePanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPhatThuongCuoiNam = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnQuanLyPhanQua = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQua = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ CẤP PHÁT PHẦN THƯỞNG");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 6, 335, 30));

        btnPhatThuongCuoiNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPhatThuongCuoiNam.setText("PHÁT THƯỞNG CUỐI NĂM");
        btnPhatThuongCuoiNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhatThuongCuoiNamActionPerformed(evt);
            }
        });
        add(btnPhatThuongCuoiNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 234, 53));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("PHÁT QUÀ DỊP ĐẶC BIỆT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 230, 54));

        btnQuanLyPhanQua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyPhanQua.setText("QUẢN LÝ PHẦN QUÀ");
        btnQuanLyPhanQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyPhanQuaActionPerformed(evt);
            }
        });
        add(btnQuanLyPhanQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 234, 52));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("QL PHÁT QUÀ DỊP ĐẶC BIỆT");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 234, 55));

        tblQua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblQua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID Nhân Khẩu", "Họ Tên", "Tổng Quà Nhận"
            }
        ));
        jScrollPane2.setViewportView(tblQua);
        if (tblQua.getColumnModel().getColumnCount() > 0) {
            tblQua.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblQua.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblQua.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 115, 541, 300));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tổng quà:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 81, -1));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 6, 103, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 51, 92, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tìm kiếm:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 81, -1));

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 278, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Tìm");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPhatThuongCuoiNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhatThuongCuoiNamActionPerformed
        // TODO add your handling code here:
        PTCuoiNamJFrame ptCuoiNam = new PTCuoiNamJFrame(parentFrame);
        ptCuoiNam.setLocationRelativeTo(null);
        ptCuoiNam.setResizable(false);
        ptCuoiNam.setVisible(true);

    }//GEN-LAST:event_btnPhatThuongCuoiNamActionPerformed

    private void btnQuanLyPhanQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyPhanQuaActionPerformed
        // TODO add your handling code here:
        QuanLyPhanQuaJFrame qlPhanQua = new QuanLyPhanQuaJFrame(parentFrame);
        qlPhanQua.setLocationRelativeTo(null);
        qlPhanQua.setResizable(false);
        qlPhanQua.setVisible(true);

    }//GEN-LAST:event_btnQuanLyPhanQuaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PTDacBietJrame phatThuong = new PTDacBietJrame(parentFrame);
        phatThuong.setLocationRelativeTo(null);
        phatThuong.setResizable(false);
        phatThuong.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DipDacBietJFrame dipDB = new DipDacBietJFrame(parentFrame);
        dipDB.setLocationRelativeTo(null);
        dipDB.setResizable(false);
        dipDB.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        // TODO add your handling code here:
//        if (txtTimKiem.getText().equals("Tìm kiếm theo tên")) {
//            txtTimKiem.setText("");
//            txtTimKiem.setFont(new Font("Segoe UI", Font.PLAIN, 14));
//        }
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
        // TODO add your handling code here:
//        if (txtTimKiem.getText().equals("")) {
//            txtTimKiem.setText("Tìm kiến theo tên");
//            txtTimKiem.setFont(new Font("Segoe UI", Font.ITALIC, 12));
//        }
    }//GEN-LAST:event_txtTimKiemFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhatThuongCuoiNam;
    private javax.swing.JButton btnQuanLyPhanQua;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblQua;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
